spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}/${DB_NAME}?${DB_SSL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    hibernate.ddl-auto: none
  mail:
    protocol: smtps
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    debug: true