spring:
  datasource:
    url: jdbc:postgresql://localhost/checklist
    username: postgres
    password: root
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate.ddl-auto: update
    properties.hibernate.jdbc.lob.non_contextual_creation: true
  mail:
    protocol: smtps
    host: smtp.gmail.com
    port: 465
    username: kgeuproject@gmail.com
    password: Root123!
    debug: true
  session:
    jdbc:
      initialize-schema: always
      table-name: SPRING_SESSION